name: CynicalCatt
description: Budding Programmer.
url: "http://CynicalCatt.github.io"
paginate: 8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:categories/:title/

gems: [jekyll-paginate]
