name: CynicalCatt
description: CynicalCatt's blog. Budding programmer, language enthusiast, gaming addict.
baseurl: ""
url: ""
paginate: 8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:categories/:title/
gems: [jekyll-paginate, jekyll-seo-tag]